### ISSUE TITLE
🎈 Roadmap: Suggestions & Ideas

### ISSUE THREAD

**Issue by kangarko** [kangarko/AutoPlay#1]
This is an continuously updated list of features to be **considered** and added in the next release(s).

## High priority
- [ ] /ap kick
- [ ] /ap pause

## Normal priority
- [ ] Sounds
- [ ] Prevent PvP when player is exempted
- [ ] Update pause button when autochanged - delay 10 ms ?
- [ ] Safeguard - prevent other ma arenas on the event world
- [ ] Database Inventory Saving
- [ ] Spectator Mode
- [ ] Statistics - Arenas Played, etc.
- [ ] Countdown Watches
- [ ] Metrics: Acqusition channel

**Feel free to comment below, but comments are cleaned regularly to keep this page clean.**

**Comment by kangarko** [comment]
Hey mibby, 

thanks for the suggestions. The voting system is great and so are the rest of them. Right now I have stuff with moving apartments so I can't get to it, but once done I will implement some of them you have suggested.

**Comment by Owizardo** [comment]
@kangarko I think this might be a similar need as Mibby. I am currently running multiverse-core where I have a separate map for the lobby on the same server. I have different command NPCs around to start the minigames you want to play. I added both Core Arenas and Puncher Arenas to my collection of minigames. 

I was hoping that the arena would let me setup multiple queues, one fore Core Arenas and another for Puncher arenas. I don't want those games or any other games to mix in together.

I would also like to see a manual way to join the queue. For example a command like /ap join #queue_name_here.

Would be great if we could also customize the list of games that can be autoplayed. For example, via the config it would be great if we could do:

#Autoplay queues
QUEUE1:
   - /pa join Puncher_Arena_name1
   - /pa join Puncher_Arena_name2
   - /pa join Puncher_Arena_name3
QUEUE2:
   - /ma join COREArena_name1
   - /ma join COREArena_name2
   - /ma join COREArena_name3

System that would work by commands to launch games could bring greater compatibility with other minigame plugins if not all.

**Comment by kangarko** [comment]
Thanks, I see how this could expand the compatibility greatly. However the other minigame plugin must handle the inventory properly, and any errors not caught by it would result in wrong inventories, players being misplaced around the world, etc. I can add the commands, but those are the precautions. Anyways, will get back to you after 19th.

**Comment by kangarko** [comment]
Had to delay it again due to works on ChatControl. Will come back later. Thank you for your understanding.

**Comment by kangarko** [comment]
@mibby not for now, I got busy with recording a video course and before I expand AutoPlay I would like

* a) either hook into the plugins hardcore directly using their methods
* or b) find a more universal approach as (suggested previously). This requires massive testing to ensure that it's stable.

Both require more time than I have until summer so honestly I have to postpone it until further notice. Thanks for understanding :)

**Comment by jamesd5** [comment]
Is the plugin GetDownPro supported?
...............................................................................................................................................................................
...............................................................................................................................................................................
I would be happy if it was :> and if there was a list of all the compatible plugins with auto play.

Thank you if you read this... Now I am just trying to get the word limit down.

**Comment by kangarko** [comment]
Nope AutoPlay is not receiving new features right now sorry.

**Comment by LucidusMC** [comment]
Any update on other minigame plugin support?  Or do you see this as only supporting KaCoding ltd. minigames?

**Comment by kangarko** [comment]
For now it only supports our minigames + MobArena. When we start taking suggestions you will see this in the update log.

**Comment by kangarko** [comment]
Closing, plugin has been discontinued, more information on SpigotMC.
